language: go
env:
    - FRIDAY_CHECKDURATION=1s
go:
    - 1.6
    - 1.7
    - 1.8
    - 1.9
before_script:
    - make init
script:
    - make test
    - make release
branches:
    only:
        - master
