language: go
env:
    - FRIDAY_TIMER_CHECKDURATION=1s
go:
    - 1.6
    - 1.7
    - 1.8
    - 1.9
before_script:
    - make init
script:
    - make build
    - make release
    - make ci-test
branches:
    only:
        - master
