# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = ["friday"]

[metadata]
codename = "friday"


[[constraint]]
  name = "github.com/emirpasic/gods"
  version = "1.9.0"

[[constraint]]
  name = "github.com/gorhill/cronexpr"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/yuin/gopher-lua"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/validator.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
